### ISSUE TITLE
Criar gerador de sentenças

### ISSUE THREAD

**Issue by AlexandreKavalerski** [AlexandreKavalerski/analisadorLexicoSintatico-exemplo#2]
Permitir ao usuário gerar uma sentença aleatória (a partir de uma base de dados de sentenças presente em um arquivo `json`). Ao clicar em um botão, o campo de entrada de sentenças é preenchido e o resultado (saída do analisador) é exibido na tela (Ex: mensagem de sucesso ou de erro).

**Comment by Qnedy** [comment]
ok
